from datetime import datetime
from pathlib import Path
import json

import joblib
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
)
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

from app.ml.preprocessing import clean_text


# Project root directory
BASE_DIR = Path(__file__).resolve().parents[2]

# Path to the SMS Spam Collection dataset
DATASET_PATH = BASE_DIR / "data" / "smsspam" / "SMSSpamCollection"

# Directory where generated model artifacts will be stored
MODEL_DIR = Path(__file__).resolve().parent / "models"

# Serialized model file
MODEL_FILE = MODEL_DIR / "spam_model.joblib"

# Model evaluation metrics file
METRICS_FILE = MODEL_DIR / "metrics.json"


def load_dataset() -> pd.DataFrame:
    """
    Load the SMS Spam Collection dataset.

    Returns:
        pd.DataFrame: Dataset with label and message columns.
    """
    df = pd.read_csv(
        DATASET_PATH,
        sep="\t",
        header=None,
        names=["label", "message"],
    )

    # Ensure column names do not contain leading or trailing spaces
    df.columns = df.columns.str.strip()

    return df


def build_metrics(y_test, predictions) -> dict:
    """
    Calculate model evaluation metrics.

    Args:
        y_test: True labels from the test dataset.
        predictions: Predicted labels generated by the trained model.

    Returns:
        dict: Model metrics, confusion matrix values, and generation timestamp.
    """
    cm = confusion_matrix(
        y_test,
        predictions,
        labels=["ham", "spam"],
    )

    return {
        "model": "TF-IDF + Multinomial Naive Bayes",
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "dataset": "SMS Spam Collection",
        "metrics": {
            "accuracy": round(accuracy_score(y_test, predictions), 4),
            "precision": round(
                precision_score(y_test, predictions, pos_label="spam"),
                4,
            ),
            "recall": round(
                recall_score(y_test, predictions, pos_label="spam"),
                4,
            ),
            "f1_score": round(
                f1_score(y_test, predictions, pos_label="spam"),
                4,
            ),
        },
        "confusion_matrix": {
            "labels": ["ham", "spam"],
            "matrix": cm.tolist(),
            "true_negatives": int(cm[0][0]),
            "false_positives": int(cm[0][1]),
            "false_negatives": int(cm[1][0]),
            "true_positives": int(cm[1][1]),
        },
    }


def save_metrics(metrics: dict) -> None:
    """
    Save model evaluation metrics as a JSON file.

    Args:
        metrics (dict): Metrics generated during model evaluation.
    """
    with open(METRICS_FILE, "w", encoding="utf-8") as file:
        json.dump(metrics, file, indent=4)


def train() -> None:
    """
    Train and persist the spam detection model.

    This function performs the complete training workflow:
    1. Load the dataset.
    2. Clean the message text.
    3. Split the dataset into training and testing subsets.
    4. Build a pipeline with TF-IDF vectorization and Multinomial Naive Bayes.
    5. Train the model.
    6. Evaluate the model.
    7. Save the trained model and evaluation metrics.
    """
    print("Loading dataset...")

    df = load_dataset()

    # Apply the same preprocessing used by the application
    df["message"] = df["message"].apply(clean_text)

    # Define input features and target variable
    X = df["message"]
    y = df["label"]

    # Split data while preserving the class distribution
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y,
    )

    # Build the ML pipeline
    pipeline = Pipeline(
        [
            ("tfidf", TfidfVectorizer()),
            ("classifier", MultinomialNB()),
        ]
    )

    print("Training model...")

    # Train the model pipeline
    pipeline.fit(X_train, y_train)

    # Generate predictions on unseen data
    predictions = pipeline.predict(X_test)

    # Calculate evaluation metrics
    metrics = build_metrics(y_test, predictions)

    print(f"Accuracy : {metrics['metrics']['accuracy']:.4f}")
    print(f"Precision: {metrics['metrics']['precision']:.4f}")
    print(f"Recall   : {metrics['metrics']['recall']:.4f}")
    print(f"F1 Score : {metrics['metrics']['f1_score']:.4f}")

    # Ensure model directory exists
    MODEL_DIR.mkdir(exist_ok=True)

    # Save trained model
    joblib.dump(pipeline, MODEL_FILE)

    # Save metrics
    save_metrics(metrics)

    print(f"Model saved at  : {MODEL_FILE}")
    print(f"Metrics saved at: {METRICS_FILE}")


if __name__ == "__main__":
    train()